import os

DOCS_DIR = r"d:\FYP\AI-Client-Hunting-OutReach-main\AI-Client-Hunting-OutReach-main\fastapi-backend\docs\ProjectDocs"

# Content definitions
content_16 = """# 16 — Full Stack SaaS Implementation & Architecture

## 16.1 Transition to Production SaaS
The project has evolved from a local minimal viable product (MVP) into a production-grade Software-as-a-Service (SaaS) platform. This architectural shift separates concerns across distinct deployment environments:
- **Frontend Layer**: Deployed on Vercel utilizing the Next.js 14 App Router.
- **Backend API Layer**: Deployed on Render utilizing FastAPI.
- **Persistence Layer**: Managed via Supabase (PostgreSQL), utilizing connection pooling (pgbouncer) for high-concurrency requests.

## 16.2 Deployment Pipeline & CORS Strategy
### Cross-Origin Resource Sharing (CORS)
To securely facilitate communication between the Vercel frontend and Render backend, the backend is configured with dynamic CORS middleware:
- `ALLOWED_ORIGINS` strictly defines domains (e.g., `https://ai-client-hunting.vercel.app`) permitted to make API calls.
- Preflight requests (`OPTIONS`) are natively handled by FastAPI's `CORSMiddleware`.

### Environment Configuration Management
Strict separation of environment variables is maintained to ensure security and flexibility:
- **Backend (.env)**: Stores `DATABASE_URL`, `SECRET_KEY`, `GOOGLE_CLIENT_SECRET`, and `RESEND_API_KEY`.
- **Frontend (.env.local)**: Stores `NEXT_PUBLIC_API_URL` to route client-side fetch requests to the correct backend endpoint dynamically.

## 16.3 High Availability & Scaling
By deploying on Vercel and Render, the system leverages edge caching and horizontal scaling. The FastAPI backend utilizes `asyncpg` combined with Supabase's transaction pooler (port 6543) to prevent connection exhaustion during concurrent web crawling and auditing tasks.
"""

content_17 = """# 17 — Frontend UI/UX Architecture (Next.js & React)

## 17.1 Modern App Router Architecture
The frontend utilizes the Next.js 14 App Router (`app/` directory) to enable Server-Side Rendering (SSR) and optimized Client-Side Routing.
- **Layouts**: `layout.js` manages the global theme and state providers.
- **Shell Patterns**: `AppShell` and `PublicShell` dynamically render sidebars and navbars based on authentication state, avoiding redundant DOM renders.

## 17.2 Premium Design Aesthetics
To meet modern SaaS standards, the UI employs:
- **Tailwind CSS**: For utility-first, responsive styling.
- **Framer Motion**: For complex micro-interactions, page transitions, and staggered list animations (e.g., Dashboard metrics rendering).
- **Glassmorphism**: Backdrop blurring and semi-transparent layers create a depth-of-field effect in the `AppShell`.
- **Theme Management**: Native Dark/Light mode switching persisting via `localStorage` and synchronized with Tailwind's `dark:` classes.

## 17.3 State Management & Auth Flow
- **useSyncExternalStore**: Used to subscribe React components to `localStorage` changes, ensuring multi-tab authentication synchronization.
- **JWT Persistence**: Access tokens are stored locally and attached to the `Authorization: Bearer <token>` header for all authenticated outbound requests.
- **Hydration Safety**: Theme toggling injects a blocking script in `<head>` to prevent Flash of Unstyled Content (FOUC) and React hydration mismatches.

## 17.4 Advanced Components
- **Rich Text Editor**: A custom WYSIWYG editor built for the Outreach generator, allowing users to format text (Bold, Italic, Alignment, Colors) before dispatching SMTP emails.
- **Dynamic Dashboards**: Real-time metric calculation components based on the user's historical campaign and audit data.
"""

content_18 = """# 18 — Machine Learning & AI Pipeline Optimization

## 18.1 Intelligent Outreach Orchestration
The core value proposition of the system relies on LLMs (Large Language Models) interpreting structured audit data and unstructured scraped data.
- **Context Injection**: The LLM is provided with a system prompt detailing the exact flaws of a prospect's website (e.g., missing SSL, poor mobile score).
- **Personalization Engine**: Using the prospect's extracted social links and business name, the LLM generates a highly contextualized cold email.

## 18.2 Fallback Parsing and Token Optimization
- **Data Pruning**: Before sending HTML DOM to the LLM or parser, boilerplate elements (navbars, footers) are stripped using BeautifulSoup to conserve context windows and reduce token costs.
- **Provider Agnostic**: The architecture supports swapping between Groq (Llama-3), OpenAI (GPT-4), or Anthropic (Claude) seamlessly via the unified inference interface.

## 18.3 Natural Language Generation (NLG) Evaluation
Emails generated by the AI agent are optimized for:
- **Deliverability**: Avoiding spam-trigger keywords.
- **Conversion Rate**: Focusing on measurable ROI (Return on Investment) based on the specific audit flaws found.
"""

content_19 = """# 19 — Advanced Authentication & OAuth Architecture

## 19.1 JWT-Based Authentication Lifecycle
The system implements a robust, stateless authentication mechanism utilizing JSON Web Tokens (JWT).
- **Algorithm**: `HS256` hashing with a securely generated `SECRET_KEY`.
- **Token Claims**: Tokens encode the user's `sub` (UUID) and `exp` (expiration timestamp) to prevent replay attacks.
- **Password Security**: Passwords are mathematically hashed using `bcrypt` (v3.2.0 for `passlib` compatibility) with appropriate salt rounds before database persistence.

## 19.2 OAuth 2.0 Integration (Google Cloud)
To facilitate seamless outreach without requiring users to share raw SMTP credentials, the platform integrates Google OAuth.
- **Consent Flow**: The backend generates an authorization URL with scopes `gmail.send`, `gmail.readonly`, and `userinfo.profile`.
- **Token Exchange**: The `/google/callback` endpoint securely exchanges the authorization code for an `access_token` and `refresh_token`.
- **At-Rest Encryption**: OAuth tokens are encrypted using `cryptography.fernet` (AES) before being stored in the Supabase database to prevent credential leakage in the event of a data breach.

## 19.3 Email Verification Workflow
- **Resend API**: Upon registration, a unique, cryptographically secure token is generated and dispatched to the user's email via the Resend API.
- **Time-Bound Validity**: Verification tokens are strictly time-bound (e.g., 24 hours), utilizing timezone-aware `datetime.now(timezone.utc)` objects in PostgreSQL (`TIMESTAMP WITH TIME ZONE`).
"""

def write_new_files():
    with open(os.path.join(DOCS_DIR, "16_Full_Stack_SaaS_Implementation.md"), "w", encoding="utf-8") as f:
        f.write(content_16)
    with open(os.path.join(DOCS_DIR, "17_Frontend_UI_UX_Architecture.md"), "w", encoding="utf-8") as f:
        f.write(content_17)
    with open(os.path.join(DOCS_DIR, "18_ML_and_AI_Pipeline_Optimization.md"), "w", encoding="utf-8") as f:
        f.write(content_18)
    with open(os.path.join(DOCS_DIR, "19_Advanced_Authentication_OAuth.md"), "w", encoding="utf-8") as f:
        f.write(content_19)

def update_toc():
    toc_path = os.path.join(DOCS_DIR, "00_TOC.md")
    with open(toc_path, "a", encoding="utf-8") as f:
        f.write("\n## Phase 4: Production SaaS & Full Stack Architecture\n")
        f.write("- **[16_Full_Stack_SaaS_Implementation.md](./16_Full_Stack_SaaS_Implementation.md)**: Vercel, Render, and Supabase deployment infrastructure.\n")
        f.write("- **[17_Frontend_UI_UX_Architecture.md](./17_Frontend_UI_UX_Architecture.md)**: Next.js App Router, Framer Motion, state management.\n")
        f.write("- **[18_ML_and_AI_Pipeline_Optimization.md](./18_ML_and_AI_Pipeline_Optimization.md)**: Advanced LLM prompting, context pruning, and NLG pipelines.\n")
        f.write("- **[19_Advanced_Authentication_OAuth.md](./19_Advanced_Authentication_OAuth.md)**: JWT lifecycles, Bcrypt hashing, Google OAuth flows, and AES encryption.\n")

if __name__ == "__main__":
    write_new_files()
    update_toc()
    print("Documentation extensively updated successfully!")
